services:
  vente-discovery-service:
    build: ./discovery-service
    container_name: vente-discovery-service
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      retries: 4
  vente-config-service:
    build: ./config-service
    container_name: vente-config-service
    ports:
      - '9999:9999'
    expose:
      - '9999'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://vente-discovery-service:8761/eureka
    depends_on:
      vente-discovery-service:
        condition: service_healthy
  vente-acheteur-service:
    build: ./acheteur-service
    container_name: vente-acheteur-service
    ports:
      - '8081:8081'
    expose:
      - '8081'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8081/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://vente-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://vente-config-service:9999
    depends_on:
      vente-config-service:
        condition: service_healthy
  vente-produit-service:
    build: ./produit-service
    container_name: vente-produit-service
    ports:
      - '8082:8082'
    expose:
      - '8082'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8082/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://vente-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://vente-config-service:9999
    depends_on:
      vente-acheteur-service:
        condition: service_healthy
  vente-vente-service:
    build: ./vente-service
    container_name: vente-vente-service
    ports:
      - '8083:8083'
    expose:
      - '8083'
    healthcheck:
      test: [ "CMD","curl","-f", "http://localhost:8083/actuator/health" ]
      interval: 10s
      retries: 4
    environment:
      - DISCOVERY_SERVICE_URL=http://vente-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://vente-config-service:9999
    depends_on:
      vente-produit-service:
        condition: service_healthy
  vente-gateway-service:
    build: ./gateway-service
    container_name: vente-gateway-service
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://vente-discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://vente-config-service:9999
    depends_on:
      vente-vente-service:
        condition:
          service_healthy
